### PR TITLE
remove compiler errors in platformio / conversion from bool to HIGH/LOW

### PR DESCRIPTION
**Pull request by bridystone**
this pull request solves compile errors in platformio
Arduino IDE is not very sensitive here.

### CODE REVIEW

**Comment by DeanIsMe** [comment]
Is there an alternative data type that can be used for compatibility with arduino and platformio? One of the goals of this project was that it was as readable and newbie-friendly as possible, and the large number of ternary operators works against that.

**Comment by bridystone** [comment]
This version works with both ArduinoIDE & platformio.
it just removes the compiler errors that ArduinoIDE seems to accept.

The code just transforms boolean into LOW/HIGH.

`boolVariable?ValueOne:ValueTwo`

just translates to:
```
if (boolVariable) {
  'use' HIGH as parameter
} else {
  'use' LOW as parameter
}
```

**Comment by DeanIsMe** [comment]
I understand your commit. My only hesitation is that the large number of ternary operators makes the code a little less readable and a little less user-friendly. Hence, it would be preferable if there was a compatible datatype that could be used for segmentOnVal and digitOnVal that can hold the values HIGH and LOW.

**Comment by bridystone** [comment]
I now understood that the root cause is just the DigitalOffVal/DigitalOnVal/... definition of bool.
This pull request only fixes the consequences...

I have created a new commit that fixes the problems root cause.
i'll create a new pull request

**Pull request closed without merging**
