### PR TITLE
Shift register implementation including an Arduino IDE Example

### PR DESCRIPTION
**Pull request by bridystone**
I've added a new Class to your library to enabled it for usage with Shift-Register.

Most of the code is reused.
Only the Actual functions doing DigitalWrite and the begin is being upgraded, 
when the child class is used.

The functions are virtual to enable refreshDisplay to choose the correct SegmentOn/Off etc. function.
if its called from SevSeg it calls the SevSeg-Functions - if its called by the SevSegShift, it calls the corresponding SevSegShift functions.

I've also attached an example in the ArduinoIDE-example folder.
it also includes a circuit layout picture

What do you think?
is it worth to be integrated in your library?

Jens

### CODE REVIEW

**Comment by DeanIsMe** [comment]
The original intention of this library was to allow the use of seven-segment displays without any additional hardware. Adding this support for shift registers does bloat the library.
That said, the library has become fairly popular and I know that a lot of people want shift register support.
I think my preferred solution would be to keep this shift-register fork of the library separate (although with a mostly compatible interface). The forks can link to each other in the README files.
What do you think?

**Comment by bridystone** [comment]
This is fine with me.
and i fully understand the approach.

I'll keep most things according to your library - and also will try to update, when you do.
i'll only update the required configuration stuff and some documentation.

i'll let you know when i've finished my stuff - and you can review, if you are fine with it.

Greatings
Jens

**Comment by bridystone** [comment]
I've now created a release for SevSegShift.
I've decided to keep the version number according to yours (with a minor/patch increase).
Let's see, if this was a good decision.

I also just kept mostly your documentation and your copyrights.
only adding stuff, when necessary.
https://github.com/DeanIsMe/SevSeg/compare/v3.4.0...bridystone:v3.4.1

Let me know, if you have some comments.
Otherwise I will publish the fork in the Arduino Library.

Greetings 
Jens

**Comment by DeanIsMe** [comment]
Great stuff! I'll add a link to SevSegShift from the SevSeg page :)
My only suggestion would be to update the README to make the 2 different configuration options (with shift registers or direct driving) more clear to people unfamiliar with the libraries. The schematic that you created is a great way to illustrate the configuration.

**Comment by bridystone** [comment]
cool.
I've updated the README a little more and added more about the Shift Registers.

Thanks for your support.

**Pull request closed without merging**
